global:
 scrape_interval: 5s
 external_labels:
   monitor: 'my-monitor'
rule_files:
 - 'alert.rules'
scrape_configs:
 - job_name: 'prometheus'
   basic_auth:
      username: chainlinkUser  # add here your Username of the prometheus authentication login
      password: ${PROMETHEUS_PASSWORD}  # add here your Password of the prometheus authentication login
   static_configs:
     - targets: ['localhost:9090']
   scheme: https
   tls_config:
     ca_file: /tls/prometheus.crt
 - job_name: 'node-exporter'
   basic_auth:
      username: chainlinkUser  # add here your Username of the node-exporter authentication login
      password: ${EXPORTER_PASSWORD}  # add here your Username of the node-exporter authentication login
   static_configs:
     - targets: ['node-exporter:9100']  # add the container ID of your running node-exporter
   scheme: https
   tls_config:
#    ca_file: /tls/prometheus.crt
#    cert_file: /tls/prometheus.crt
#    key_file: /tls/prometheus.key
     insecure_skip_verify: true
 - job_name: 'chainlink_p1'
   static_configs:
     - targets: ['chainlink-node:6688']  # add the container ID of your running Node and if you use a diffrent port you can also configure it
   scheme: http
   tls_config:
     insecure_skip_verify: true
