version: "3.8"

services:

  chainlink-node-1:
    container_name: "primary-node"
    build: chainlink/
    env_file:
      - chainlink/.env
    restart: on-failure
    ports:
      - 6689:6689
    volumes:
      - chainlink:/chainlink

  ipfs-daemon:
    container_name: "ipfs-daemon"
    build: ipfs/
    restart: on-failure
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8080:8080"
    depends_on:
      - chainlink-node-1

  external-adapter:
    container_name: "arbol-adapter"
    build: adapter/
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - adapter:/adapter
    depends_on:
      - chainlink-node-1
      - ipfs-daemon

  # chainlink-node-2:
  #   container_name: "backup-node"
  #   build: chainlink/
  #   env_file:
  #     - chainlink/backup.env
  #   restart: on-failure
  #   ports:
  #     - 6689:6689
  #   volumes:
  #     - chainlink:/chainlink
  #   depends_on:
  #     - chainlink-node-1
    
volumes:
  chainlink: 
  adapter: