{
 "title": "Chainlink",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Eth-Balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eth_balance" }
   ]
  },
  {
   "title": "Current Head",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "head_tracker_current_head" }
   ]
  },
  {
   "title": "New heads per minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(head_tracker_heads_received{job=~\"chainlink_p.*\"}[1m])*60"
    }
   ]
  },
  {
   "title": "New heads per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(head_tracker_heads_received{job=~\"chainlink_p.*\"}[1m])*60"
    }
   ]
  },
  {
   "title": "Node logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\"}"
    }
   ]
  },
  {
   "title": "Container uptime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Current Head increase",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(head_tracker_current_head{job=~\"chainlink_p.*\"}[1m])*60",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Gas Price",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gas_updater_set_gas_price" }
   ]
  },
  {
   "title": "Gas Price Percentiles",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gas_updater_all_gas_price_percentiles{percentile!=\"100%\",job=~\"chainlink_p.*\"}/1000000000",
     "legendFormat": "{{percentile}}"
    }
   ]
  },
  {
   "title": "Job Proposals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "feeds_job_proposal_requests" }
   ]
  },
  {
   "title": "Eth Balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eth_balance" }
   ]
  },
  {
   "title": "Run Queue Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pipeline_runs_queued" }
   ]
  }
 ]
}