version: "3.8"

services:
  chainlink-node-1:
    container_name: primary-node
    image: 574269834288.dkr.ecr.us-east-1.amazonaws.com/chainlink-node-1
    x-aws-pull_credentials: "arn:aws:secretsmanager:us-east-1:574269834288:secret:docker-ecr-WfeJ0H"
    env_file:
      - chainlink/.env
    volumes:
      - chainlink:/chainlink

  ipfs-daemon:
    container_name: ipfs-daemon
    image: 574269834288.dkr.ecr.us-east-1.amazonaws.com/ipfs-daemon
    x-aws-pull_credentials: "arn:aws:secretsmanager:us-east-1:574269834288:secret:docker-ecr-WfeJ0H"
    volumes:
      - /export
      - /data/ipfs
    depends_on:
      - chainlink-node-1
    healthcheck:
      test: ipfs swarm peers || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  external-adapter:
    environment:
      - PYTHONUNBUFFERED=1
    container_name: arbol-adapter
    image: 574269834288.dkr.ecr.us-east-1.amazonaws.com/external-adapter
    x-aws-pull_credentials: "arn:aws:secretsmanager:us-east-1:574269834288:secret:docker-ecr-WfeJ0H"
    volumes:
      - adapter:/adapter
      - "../web_app/packages/contracts/src/logs:/adapter/logs"
      - "../smart_contracts/hardhat/SROs:/adapter/SROs"
    depends_on:
      ipfs-daemon:
        condition: service_healthy
      chainlink-node-1:
        condition: service_started

volumes:
  adapter:
    driver_opts:
    # Filesystem configuration
    backup_policy: ENABLED
    lifecycle_policy: AFTER_14_DAYS
    performance_mode: maxIO
    throughput_mode: provisioned
    provisioned_throughput: 1
  export:
    driver_opts:
    # Filesystem configuration
    backup_policy: ENABLED
    lifecycle_policy: AFTER_14_DAYS
    performance_mode: maxIO
    throughput_mode: provisioned
    provisioned_throughput: 1
  data:
    driver_opts:
    # Filesystem configuration
    backup_policy: ENABLED
    lifecycle_policy: AFTER_14_DAYS
    performance_mode: maxIO
    throughput_mode: provisioned
    provisioned_throughput: 1
  chainlink:
    driver_opts:
    # Filesystem configuration
    backup_policy: ENABLED
    lifecycle_policy: AFTER_14_DAYS
    performance_mode: maxIO
    throughput_mode: provisioned
    provisioned_throughput: 1
