version: "3.8"

services:
  chainlink-node-1:
    network_mode: "host"
    container_name: "primary-node"
    build: chainlink/
    env_file:
      - chainlink/.env
    # ports:
    #   - 6689:6689
    volumes:
      - "./chainlink:/chainlink"

  ipfs-daemon:
    network_mode: "host"
    container_name: "ipfs-daemon"
    build: "ipfs/"
    volumes:
      - "./ipfs/export:/export"
      - "./ipfs/data/ipfs:/data/ipfs"
    depends_on:
      - chainlink-node-1

  external-adapter:
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: "host"
    container_name: "arbol-adapter"
    build: "adapter/"
    volumes:
      - "./adapter:/adapter"
    depends_on:
      # - chainlink-node-1
      - ipfs-daemon

    # for whitelisting contracts against oracle jobs
    # psql -d "host=nodestorage.cluster-cxcluinxlxok.us-east-1.rds.amazonaws.com port=5432 dbname=EthereumKovan user=NodeOperator" -W