version: "3.8"

services:
  ipfs-daemon:
    network: bridge
    container_name: ipfs-daemon
    build: ipfs
    ports:
      - 4001:4001
      - 5001:5001
    volumes:
      - /export
      - /data/ipfs

  arbol-adapter:
    network: bridge
    container_name: arbol-adapter
    build: adapter
    ports:
      - 8000:8000

volumes:
  export:
  data:
