version: "3.8"

services:
  chainlink-node-1:
    network_mode: host
    container_name: primary-node
    build: chainlink/
    env_file:
      - chainlink/.env
    volumes:
      - chainlink:/chainlink

  ipfs-daemon:
    network_mode: host
    container_name: ipfs-daemon
    build: ipfs/
    volumes:
      - /export
      - /data/ipfs
    depends_on:
      - chainlink-node-1
    restart: on-failure
    healthcheck:
      test: ipfs swarm peers || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  external-adapter:
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: host
    container_name: arbol-adapter
    build: adapter/
    volumes:
      - adapter:/adapter
    restart: on-failure
    depends_on:
      ipfs-daemon:
        condition: service_healthy
      chainlink-node-1:
        condition: service_started

volumes:
  adapter:
  export:
  data:
  chainlink:
