version: "3.8"

services:
  chainlink-node-1:
    container_name: primary-node
    image: ${DOCKER_REGISTRY}/chainlink-node-1:${IMAGE_TAG}
    env_file:
      - chainlink/.env
    volumes:
      - chainlink:/chainlink

  ipfs-daemon:
    container_name: ipfs-daemon
    image: ${DOCKER_REGISTRY}/ipfs-daemon:${IMAGE_TAG}
    volumes:
      - /export
      - /data/ipfs
    depends_on:
      - chainlink-node-1
    healthcheck:
      test: ipfs swarm peers || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  external-adapter:
    environment:
      - PYTHONUNBUFFERED=1
    container_name: arbol-adapter
    image: ${DOCKER_REGISTRY}/external-adapter:${IMAGE_TAG}
    volumes:
      - adapter:/adapter
      - "../web_app/packages/contracts/src/logs:/adapter/logs"
      - "../smart_contracts/hardhat/SROs:/adapter/SROs"
    depends_on:
      ipfs-daemon:
        condition: service_healthy
      chainlink-node-1:
        condition: service_started

volumes:
  adapter:
  export:
  data:
  chainlink:
