type                = "directrequest"
schemaVersion       = 1
name                = "solidity adapter test 1"
contractAddress     = "0xe9d0d0332934c269132e53c03D3fD63EbA41aae0"
observationSource   = """
    ds          [type="bridge" name="arbol-dapp" requestData="{\\"data\\":{\\"program\\": \\"cambodia_rainfall\\", \\"params\\":{\\"dataset\\": $(dataset), \\"opt_type\\": $(opt_type), \\"locations\\": $(locations), \\"strike\\": $(strike), \\"limit\\": $(limit), \\"exhaust\\": $(exhaust)}}}"]
    ds_parse    [type=jsonparse path="result"]

    ds -> ds_parse
"""
