on:
  push:
    branches:
      - feat/*

name: Deployment

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get .env secrets
      uses: say8425/aws-secrets-manager-actions@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        SECRET_NAME: dapp
        OUTPUT_PATH: './chainlink_node/chainlink/.env'
    
    - name: Translate ENV variables
      run: |
        printenv

    - name: Get API secrets
      env:
        API_SECRETS: ${{ secrets.API }}
      run: printf "$API_SECRETS" base64 --decode > ./chainlink_node/chainlink/.api

    - name: Get Password secret
      env:
        PASSWORD_SECRET: ${{ secrets.PASSWORD }}
      run: printf "$PASSWORD_SECRET" base64 --decode > ./chainlink_node/chainlink/.password

    - name: Get TLS cert
      env:
        TLS_CERT_SECRET: ${{ secrets.TLS_CERT }}
      run: echo "$TLS_CERT_SECRET" base64 --decode > ./chainlink_node/chainlink/tls/server.crt

    - name: Get TLS key
      env:
        TLS_KEY_SECRET: ${{ secrets.TLS_KEY }}
      run: echo "$TLS_KEY_SECRET" base64 --decode > ./chainlink_node/chainlink/tls/server.key

    - name: Create and set ECS context
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export AWS_REGION=us-east-1
        docker context create ecs dappecs --from-env
        docker context use dappecs

    - name: Build
      run: docker compose build --project-directory ./chainlink_node -f docker-compose.aws.yml

    - name: Deploy
      run: docker compose up
      